version: "3"
services:
  frontend:
    image: minju7346/docker-frontend
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    mem_limit: 128m
    environment:
      - WDS_SOCKET_PORT=0

  nginx: 
    restart: always
    image: minju7346/docker-nginx
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - "80:80"
    mem_limit: 128m
    links:
      - frontend
      - backend

  backend:
    image: minju7346/docker-backend
    build: 
      dockerfile: Dockerfile.dev
      context: ./backend
    mem_limit: 128m
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment: 
      MYSQL_HOST: docker-fullstack-mysql.cob9hpevtink.ap-northeast-2.rds.amazonaws.com
      MYSQL_USER: root 
      MYSQL_ROOT_PASSWORD: 12341234
      MYSQL_DATABASE: myapp
      MYSQL_PORT: 3306   

  # mysql:
  #   platform: linux/x86_64
  #   build: ./mysql
  #   restart: unless-stopped
  #   container_name: mysql
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./mysql/mysql_data:/var/lib/mysql
  #     - ./mysql/sqls/:/docker-entrypoint-initdb.d/
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 1234
  #     MYSQL_DATABASE: myapp